### ISSUE TITLE
Compilation errors in Storyboard

### ISSUE THREAD

**Issue by namnatulco** [riebl/artery#3]
Hi!

I managed to compile and run artery, but only after disabling the storyboard component (by commenting out the respective lines in `CMakeLists.txt` and `scenarios/storyboard/CMakeLists.txt`).

The following error occurs if I try to compile with the storyboard target:
```
/home/namnatulco/simulation/artery/src/artery/storyboard/Storyboard.cc: In member function ‘virtual void Storyboard::initialize(int)’:
/home/namnatulco/simulation/artery/src/artery/storyboard/Storyboard.cc:26:43: error: ‘initstoryboard’ was not declared in this scope
     PyImport_AppendInittab("storyboard", &initstoryboard);
                                           ^
/home/namnatulco/simulation/artery/src/artery/storyboard/Storyboard.cc:27:41: error: ‘inittimeline’ was not declared in this scope
     PyImport_AppendInittab("timeline", &inittimeline);
                                         ^
src/artery/storyboard/CMakeFiles/storyboard.dir/build.make:254: recipe for target 'src/artery/storyboard/CMakeFiles/storyboard.dir/Storyboard.cc.o' failed
gmake[2]: *** [src/artery/storyboard/CMakeFiles/storyboard.dir/Storyboard.cc.o] Error 1
CMakeFiles/Makefile2:239: recipe for target 'src/artery/storyboard/CMakeFiles/storyboard.dir/all' failed
gmake[1]: *** [src/artery/storyboard/CMakeFiles/storyboard.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```
I took a look at the code, and I don't really see an obvious fix -- `initstoryboard` and `inittimeline` don't exist anywhere in the source tree (according to `grep -r`). I also checked the header files for similarly named variables, but nothing turned up.

Am I missing something, or is the `storyboard` target not supposed to be functional yet?

**Comment by riebl** [comment]
The storyboard should be functional, other behaviour is clearly a bug.
`initX` functions are declared by the `BOOST_PYTHON_MODULE` macros located in PythonModule.h
I have just pushed e72f16fae050d05a86cb65f68444c42c81c78bc3, which introduces CMake option `WITH_STORYBOARD` so the optional storyboard feature can be easily disabled.

**Comment by namnatulco** [comment]
For a moment I thought the cause might be that I didn't have the `boost-python3-devel` package installed, but that doesn't appear to be the case; compilation still fails.

**Comment by riebl** [comment]
This issue only occurs when Python 3 is used (tested with Python 3.5). It compiles fine with Python 2.7 library and headers. Will be fixed.

**Comment by riebl** [comment]
Can you please try the storyboard_py3 branch if it fixes this issue?

**Comment by namnatulco** [comment]
Works! Thanks!

**Comment by riebl** [comment]
Merged fix into master branch with 32b9d298ea7e3baf99c1e181d32a282e9b34419d
